/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocasRouteImport } from './routes/trocas'
import { Route as PeneirasRouteImport } from './routes/peneiras'
import { Route as MotivosRouteImport } from './routes/motivos'
import { Route as MoinhosRouteImport } from './routes/moinhos'
import { Route as IndexRouteImport } from './routes/index'

const TrocasRoute = TrocasRouteImport.update({
  id: '/trocas',
  path: '/trocas',
  getParentRoute: () => rootRouteImport,
} as any)
const PeneirasRoute = PeneirasRouteImport.update({
  id: '/peneiras',
  path: '/peneiras',
  getParentRoute: () => rootRouteImport,
} as any)
const MotivosRoute = MotivosRouteImport.update({
  id: '/motivos',
  path: '/motivos',
  getParentRoute: () => rootRouteImport,
} as any)
const MoinhosRoute = MoinhosRouteImport.update({
  id: '/moinhos',
  path: '/moinhos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/moinhos': typeof MoinhosRoute
  '/motivos': typeof MotivosRoute
  '/peneiras': typeof PeneirasRoute
  '/trocas': typeof TrocasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/moinhos': typeof MoinhosRoute
  '/motivos': typeof MotivosRoute
  '/peneiras': typeof PeneirasRoute
  '/trocas': typeof TrocasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/moinhos': typeof MoinhosRoute
  '/motivos': typeof MotivosRoute
  '/peneiras': typeof PeneirasRoute
  '/trocas': typeof TrocasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/moinhos' | '/motivos' | '/peneiras' | '/trocas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/moinhos' | '/motivos' | '/peneiras' | '/trocas'
  id: '__root__' | '/' | '/moinhos' | '/motivos' | '/peneiras' | '/trocas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MoinhosRoute: typeof MoinhosRoute
  MotivosRoute: typeof MotivosRoute
  PeneirasRoute: typeof PeneirasRoute
  TrocasRoute: typeof TrocasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocas': {
      id: '/trocas'
      path: '/trocas'
      fullPath: '/trocas'
      preLoaderRoute: typeof TrocasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peneiras': {
      id: '/peneiras'
      path: '/peneiras'
      fullPath: '/peneiras'
      preLoaderRoute: typeof PeneirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motivos': {
      id: '/motivos'
      path: '/motivos'
      fullPath: '/motivos'
      preLoaderRoute: typeof MotivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moinhos': {
      id: '/moinhos'
      path: '/moinhos'
      fullPath: '/moinhos'
      preLoaderRoute: typeof MoinhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MoinhosRoute: MoinhosRoute,
  MotivosRoute: MotivosRoute,
  PeneirasRoute: PeneirasRoute,
  TrocasRoute: TrocasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
